import type { Exercise } from "../types";

export const back: Exercise[] = [
  {
    slug: "bent-over-barbell-row",
    name: "Bent-over Barbell Row",
    gear: "Barbell",
    pattern: "Horizontal pull",
    primary: ["lats", "upperBack"],
    secondary: ["biceps", "rearDelts", "lowerBack"],
    tempo: 3,
    setup: [
      { part: "Grip width", text: "Just outside shoulder width, overhand." },
      { part: "Picking up the bar", text: "If it's on the floor, set up like a deadlift: hinge at the hips, flat back, then stand it up before hinging forward into the row position. If it's on rack pins, set them around hip height so you don't have to bend down for it." },
    ],
    bodyPosition: [
      { part: "Head", text: "Neutral, eyes down toward the floor a little ahead of you." },
      { part: "Torso", text: "Hinged forward to about 45° or a bit lower — held there the whole set." },
      { part: "Shoulder blades", text: "Pulled together as the bar arrives at your body." },
      { part: "Elbows", text: "Drive back and past your ribs, leading the pull." },
      { part: "Lower back", text: "Braced flat, no rounding." },
      { part: "Knees", text: "Softly bent, not locked straight." },
    ],
    cues: [
      "Hinge at your hips to about 45° or a bit lower. Knees softly bent. Hold that angle the whole set.",
      "Pull the bar to your lower ribs or belly button, not your chest.",
      "Lead with your elbows. Drive them back, past your ribs — don't just pull with your hands.",
      "Brace hard. Your lower back's job here is to stay still.",
    ],
    mistakes: [
      "Standing up a little on every rep so the torso angle rises with the weight — that's a cheat rep.",
      "Rounding the lower back under load.",
      "Yanking with the biceps and never actually retracting the shoulder blades.",
    ],
  },

  {
    slug: "assisted-pull-up",
    name: "Assisted Pull-up",
    aka: "Machine assisted pull-up",
    gear: "Machine",
    pattern: "Vertical pull",
    primary: ["lats"],
    secondary: ["biceps", "upperBack"],
    tempo: 3.4,
    setup: [
      { part: "Assistance weight", text: "More weight on the pin means more help. Start heavy enough that you can do 6–10 controlled reps — around 70–80% of your bodyweight in assist is a common starting point — and reduce it as you get stronger." },
      { part: "Knee pad", text: "Adjust it so your knees rest on it comfortably once you're kneeling, with your arms fully stretched overhead to the handles." },
      { part: "Grip", text: "Slightly wider than shoulder width, overhand." },
    ],
    bodyPosition: [
      { part: "Head", text: "Neutral, eyes forward." },
      { part: "Shoulders", text: "Pulled down away from your ears before you start pulling with the arms." },
      { part: "Chest", text: "Driving up toward the bar." },
      { part: "Elbows", text: "Pull down and back, not forward." },
      { part: "Core", text: "Braced so the body doesn't swing." },
      { part: "Knees", text: "Resting on the assist pad, relaxed." },
    ],
    cues: [
      "Start from a dead hang, shoulders pulled down. The first move is your shoulder blades, before your arms.",
      "Pull your chest toward the bar, not your chin over it. That keeps your lats working.",
      "Pick the least assistance weight you can control. More assist weight makes it easier.",
      "Lower all the way down under control. This part matters most.",
    ],
    mistakes: [
      "Kipping or bouncing off the knee pad.",
      "Stopping halfway down and never reaching a full hang.",
      "Shrugging the shoulders up at the bottom instead of staying packed.",
    ],
  },

  {
    slug: "lat-pulldown-wide",
    name: "Lat Pulldown, Wide Grip",
    gear: "Cable",
    pattern: "Vertical pull",
    primary: ["lats"],
    secondary: ["biceps", "upperBack"],
    tempo: 3,
    setup: [
      { part: "Thigh pad", text: "Lower it and slide your thighs under before you grab the bar, then it should press snugly on top of your thighs — that's what locks you in place." },
      { part: "Seat height", text: "Set so your feet are flat on the floor, knees at about 90°, and you can reach the bar with arms fully extended." },
      { part: "Grip width", text: "A little wider than shoulder width on the bar." },
    ],
    bodyPosition: [
      { part: "Head", text: "Neutral, eyes forward — not tilted back to watch the bar." },
      { part: "Torso", text: "Leaned back about 15° and held there." },
      { part: "Chest", text: "Lifted up toward the bar." },
      { part: "Shoulders", text: "Down, not shrugged up toward your ears." },
      { part: "Elbows", text: "Drive down toward your back pockets." },
      { part: "Hips", text: "Planted on the seat, thighs locked under the pads." },
    ],
    cues: [
      "Grip a little wider than shoulder width. Going much wider doesn't add more lat work.",
      "Lean back slightly, about 15°, and hold it. Chest up toward the bar.",
      "Pull to the top of your chest. Think: elbows into your back pockets.",
      "Let the bar rise all the way back up for a full stretch.",
    ],
    mistakes: [
      "Pulling behind the neck — no upside, real shoulder risk.",
      "Rocking back and forth so it turns into a row with momentum.",
      "Curling the bar down with the arms and never feeling the lats.",
    ],
  },

  {
    slug: "close-grip-lat-pulldown",
    name: "Close-Grip Lat Pulldown",
    aka: "Small-bar pulldown",
    gear: "Cable",
    pattern: "Vertical pull",
    primary: ["lats"],
    secondary: ["biceps", "upperBack"],
    tempo: 3,
    setup: [
      { part: "Thigh pad", text: "Lower it over your thighs before you grab the bar, snug but not painfully tight." },
      { part: "Seat height", text: "Feet flat, knees at about 90°, bar reachable with your arms fully extended." },
      { part: "Bar", text: "Swap the wide bar for the short close-grip bar or handle." },
    ],
    bodyPosition: [
      { part: "Head", text: "Neutral, eyes forward." },
      { part: "Torso", text: "Leaned back slightly, held steady all set." },
      { part: "Chest", text: "Lifted toward the bar." },
      { part: "Elbows", text: "Tracking close to your ribs, pulling the bar to your sternum." },
      { part: "Shoulders", text: "Stretched fully at the top of each rep, then pulled down and back." },
      { part: "Hips", text: "Planted on the seat, legs locked under the pads." },
    ],
    cues: [
      "Hands roughly shoulder-width on the short bar. Elbows track close to your ribs.",
      "Pull the bar all the way down to your sternum. The close grip gives you more range, so use it.",
      "Lean back slightly, the same as the wide-grip version. Hold that angle the whole set.",
      "Let your arms stretch fully at the top before the next rep.",
    ],
    mistakes: [
      "Leaning back progressively further as you fatigue.",
      "Letting the elbows drift out wide, which turns it back into a wide pulldown.",
      "Half reps at the top, cutting off the stretch.",
    ],
  },

  {
    slug: "seated-row-machine",
    name: "Seated Row Machine",
    gear: "Machine",
    pattern: "Horizontal pull",
    primary: ["upperBack", "lats"],
    secondary: ["biceps", "rearDelts"],
    tempo: 3,
    setup: [
      { part: "Chest pad", text: "Set its distance so you can reach the handles with straight arms and shoulders pulled forward, without rounding your lower back to get there." },
      { part: "Footplate", text: "Feet flat on the plate or floor, knees slightly bent, about shoulder width." },
      { part: "Handles", text: "Set to be roughly level with your mid-chest when you're seated tall." },
    ],
    bodyPosition: [
      { part: "Head", text: "Neutral, eyes forward." },
      { part: "Chest", text: "Against the pad if there is one, upright and still." },
      { part: "Shoulder blades", text: "Pulled together at the end of the pull, then let travel forward for the stretch." },
      { part: "Elbows", text: "Close to the body for more mid-back, wider for more rear delt." },
      { part: "Lower back", text: "Stays still — no leaning back to help the pull." },
      { part: "Feet", text: "Braced against the footplate." },
    ],
    cues: [
      "Chest against the pad if there is one. Torso upright and still. Only your arms and shoulder blades move.",
      "Pull the handles to your lower ribs. Hold the squeeze for a beat.",
      "Let your shoulder blades travel forward at the end of each rep for a full stretch. Don't round your lower back.",
      "Keep your elbows close to your body for more mid-back work, or wide for more rear delt.",
    ],
    mistakes: [
      "Rowing with the torso — leaning back on the pull and forward on the return.",
      "Shrugging the traps up instead of pulling the blades together.",
      "Cutting the stretch short and staying bunched up at the front.",
    ],
  },

  {
    slug: "straight-arm-pulldown",
    name: "Straight-Arm Pulldown",
    gear: "Cable",
    pattern: "Lat isolation",
    primary: ["lats"],
    secondary: ["core", "triceps"],
    tempo: 3,
    setup: [
      { part: "Pulley height", text: "Set to the highest position, bar or rope attached." },
      { part: "Starting stance", text: "Stand facing the machine, far enough back that your arms are overhead and slightly in front of you to start." },
    ],
    bodyPosition: [
      { part: "Head", text: "Neutral, eyes forward." },
      { part: "Torso", text: "Hinged forward slightly, held steady — no rocking." },
      { part: "Shoulders", text: "The only joint that moves; drive them down toward your hips." },
      { part: "Elbows", text: "Nearly straight, with a fixed soft bend the whole rep." },
      { part: "Core", text: "Braced to keep the torso still." },
    ],
    cues: [
      "Hinge forward slightly. Arms nearly straight, with a fixed soft bend in your elbows.",
      "Sweep the bar down in a big arc to your thighs. Only your shoulders should move.",
      "Squeeze your lats hard at the bottom. Let your arms rise back overhead for a full stretch.",
      "Use a light weight. If you need to bend your elbows to move it, it's too heavy.",
    ],
    mistakes: [
      "Bending the elbows and turning it into a triceps pushdown.",
      "Standing bolt upright, which cuts the range in half.",
      "Rocking the torso to drive the bar down.",
    ],
  },

  {
    slug: "back-extension",
    name: "Back Extension",
    aka: "45° hyperextension — hold a plate to add load",
    gear: "Hyper bench",
    pattern: "Hip hinge",
    primary: ["hamstrings", "glutes", "lowerBack"],
    secondary: ["core"],
    tempo: 3.2,
    setup: [
      { part: "Pad height", text: "Set it just below your hip bones, not higher up your stomach — too high and you can't hinge freely, so your lower back does all the work." },
      { part: "Foot plate", text: "Tuck your ankles under the rollers or pads with your feet flat." },
    ],
    bodyPosition: [
      { part: "Head", text: "In line with your spine, eyes toward the floor." },
      { part: "Back", text: "One straight line from head to heels the whole rep." },
      { part: "Hips", text: "The joint that folds — the pad sits just below your hip bones." },
      { part: "Glutes", text: "Squeezed hard at the top." },
      { part: "Knees", text: "Soft, not locked." },
    ],
    cues: [
      "Set the pad just below your hip bones so you can hinge freely. Too high, and your lower back does all the work.",
      "Fold at your hips. Keep your spine in one straight line from head to heels.",
      "Come up until your body is in line with your legs, then stop. Don't arch up past straight.",
      "Squeeze your glutes at the top. Start with just your bodyweight, then hug a plate to your chest once that's easy.",
    ],
    mistakes: [
      "Cranking into hyperextension at the top, which is where people tweak their back.",
      "Rounding down through the spine instead of hinging at the hip.",
      "Jerking up with momentum, especially once you add a plate.",
    ],
  },

  {
    slug: "shrugs",
    name: "Shrugs",
    gear: "Barbell / Dumbbells",
    pattern: "Scapular elevation",
    primary: ["traps"],
    secondary: ["forearms"],
    tempo: 2.6,
    setup: [
      { part: "Grip", text: "Shoulder width, overhand, arms straight — pick the bar up like the top of a deadlift." },
    ],
    bodyPosition: [
      { part: "Head", text: "Neutral, not craning forward as you shrug." },
      { part: "Shoulders", text: "Rise straight up toward your ears, then drop all the way down between reps." },
      { part: "Arms", text: "Straight, just acting as hooks — no pulling with the biceps." },
      { part: "Torso", text: "Upright and still." },
    ],
    cues: [
      "Shrug straight up toward your ears. Don't roll your shoulders.",
      "Pause for a second at the top. That squeeze is the whole exercise.",
      "Keep your arms straight, just acting as hooks. Don't pull with your biceps.",
      "Let your shoulders drop all the way down between reps for a full stretch.",
    ],
    mistakes: [
      "Rolling the shoulders backward — adds nothing and irritates the joint.",
      "Bouncing tiny reps with far too much weight.",
      "Craning the neck forward as you shrug.",
    ],
  },
];
