import type { Exercise } from "../types";

export const back: Exercise[] = [
  {
    slug: "bent-over-barbell-row",
    name: "Bent-over Barbell Row",
    gear: "Barbell",
    pattern: "Horizontal pull",
    primary: ["lats", "upperBack"],
    secondary: ["biceps", "rearDelts", "lowerBack"],
    tempo: 3,
    bodyPosition: [
      { part: "Head", text: "Neutral, eyes down toward the floor a little ahead of you." },
      { part: "Torso", text: "Hinged forward to about 45° or a bit lower — held there the whole set." },
      { part: "Shoulder blades", text: "Pulled together as the bar arrives at your body." },
      { part: "Elbows", text: "Drive back and past your ribs, leading the pull." },
      { part: "Lower back", text: "Braced flat, no rounding." },
      { part: "Knees", text: "Softly bent, not locked straight." },
    ],
    cues: [
      "Hinge at the hips to roughly 45° or a bit lower, knees softly bent, and hold that torso angle for the whole set.",
      "Pull the bar to your lower ribs or belly button, not your chest.",
      "Lead with the elbows and think about driving them back and past your ribs, not about pulling with the hands.",
      "Brace hard. The lower back's job here is to not move.",
    ],
    mistakes: [
      "Standing up a little on every rep so the torso angle rises with the weight — that's a cheat rep.",
      "Rounding the lower back under load.",
      "Yanking with the biceps and never actually retracting the shoulder blades.",
    ],
  },

  {
    slug: "assisted-pull-up",
    name: "Assisted Pull-up",
    aka: "Machine assisted pull-up",
    gear: "Machine",
    pattern: "Vertical pull",
    primary: ["lats"],
    secondary: ["biceps", "upperBack"],
    tempo: 3.4,
    bodyPosition: [
      { part: "Head", text: "Neutral, eyes forward." },
      { part: "Shoulders", text: "Pulled down away from your ears before you start pulling with the arms." },
      { part: "Chest", text: "Driving up toward the bar." },
      { part: "Elbows", text: "Pull down and back, not forward." },
      { part: "Core", text: "Braced so the body doesn't swing." },
      { part: "Knees", text: "Resting on the assist pad, relaxed." },
    ],
    cues: [
      "Start from a dead hang with the shoulders pulled down — the first move is the shoulder blades, before the arms.",
      "Pull your chest toward the bar rather than your chin over it; that keeps the lats working.",
      "Pick the least assistance you can control. More assist weight = easier.",
      "Lower all the way down under control; the negative is most of the value here.",
    ],
    mistakes: [
      "Kipping or bouncing off the knee pad.",
      "Stopping halfway down and never reaching a full hang.",
      "Shrugging the shoulders up at the bottom instead of staying packed.",
    ],
  },

  {
    slug: "lat-pulldown-wide",
    name: "Lat Pulldown, Wide Grip",
    gear: "Cable",
    pattern: "Vertical pull",
    primary: ["lats"],
    secondary: ["biceps", "upperBack"],
    tempo: 3,
    bodyPosition: [
      { part: "Head", text: "Neutral, eyes forward — not tilted back to watch the bar." },
      { part: "Torso", text: "Leaned back about 15° and held there." },
      { part: "Chest", text: "Lifted up toward the bar." },
      { part: "Shoulders", text: "Down, not shrugged up toward your ears." },
      { part: "Elbows", text: "Drive down toward your back pockets." },
      { part: "Hips", text: "Planted on the seat, thighs locked under the pads." },
    ],
    cues: [
      "Grip a little wider than shoulder width — much wider just shortens the range without adding lat work.",
      "Slight lean back, about 15°, and hold it. Chest up toward the bar.",
      "Pull to the top of your chest and think 'elbows into your back pockets'.",
      "Let the bar travel all the way up and let the shoulder blades rise at the top for a full stretch.",
    ],
    mistakes: [
      "Pulling behind the neck — no upside, real shoulder risk.",
      "Rocking back and forth so it turns into a row with momentum.",
      "Curling the bar down with the arms and never feeling the lats.",
    ],
  },

  {
    slug: "close-grip-lat-pulldown",
    name: "Close-Grip Lat Pulldown",
    aka: "Small-bar pulldown",
    gear: "Cable",
    pattern: "Vertical pull",
    primary: ["lats"],
    secondary: ["biceps", "upperBack"],
    tempo: 3,
    bodyPosition: [
      { part: "Head", text: "Neutral, eyes forward." },
      { part: "Torso", text: "Leaned back slightly, held steady all set." },
      { part: "Chest", text: "Lifted toward the bar." },
      { part: "Elbows", text: "Tracking close to your ribs, pulling the bar to your sternum." },
      { part: "Shoulders", text: "Stretched fully at the top of each rep, then pulled down and back." },
      { part: "Hips", text: "Planted on the seat, legs locked under the pads." },
    ],
    cues: [
      "Hands roughly shoulder-width on the short bar, elbows tracking close to the ribs.",
      "The close grip gives you more range — use it, and pull the bar right down to the sternum.",
      "Same lean-back as the wide version, held steady the whole set.",
      "Stretch fully at the top before the next rep.",
    ],
    mistakes: [
      "Leaning back progressively further as you fatigue.",
      "Letting the elbows drift out wide, which turns it back into a wide pulldown.",
      "Half reps at the top, cutting off the stretch.",
    ],
  },

  {
    slug: "seated-row-machine",
    name: "Seated Row Machine",
    gear: "Machine",
    pattern: "Horizontal pull",
    primary: ["upperBack", "lats"],
    secondary: ["biceps", "rearDelts"],
    tempo: 3,
    bodyPosition: [
      { part: "Head", text: "Neutral, eyes forward." },
      { part: "Chest", text: "Against the pad if there is one, upright and still." },
      { part: "Shoulder blades", text: "Pulled together at the end of the pull, then let travel forward for the stretch." },
      { part: "Elbows", text: "Close to the body for more mid-back, wider for more rear delt." },
      { part: "Lower back", text: "Stays still — no leaning back to help the pull." },
      { part: "Feet", text: "Braced against the footplate." },
    ],
    cues: [
      "Chest against the pad if the machine has one, torso upright and still — the movement is arms and shoulder blades only.",
      "Pull the handles to your lower ribs and hold the squeeze for a beat.",
      "Let the shoulder blades travel forward at the end of each rep for a full stretch, without rounding the lower back.",
      "Elbows stay close to the body for more mid-back, out wide for more rear delt.",
    ],
    mistakes: [
      "Rowing with the torso — leaning back on the pull and forward on the return.",
      "Shrugging the traps up instead of pulling the blades together.",
      "Cutting the stretch short and staying bunched up at the front.",
    ],
  },

  {
    slug: "straight-arm-pulldown",
    name: "Straight-Arm Pulldown",
    gear: "Cable",
    pattern: "Lat isolation",
    primary: ["lats"],
    secondary: ["core", "triceps"],
    tempo: 3,
    bodyPosition: [
      { part: "Head", text: "Neutral, eyes forward." },
      { part: "Torso", text: "Hinged forward slightly, held steady — no rocking." },
      { part: "Shoulders", text: "The only joint that moves; drive them down toward your hips." },
      { part: "Elbows", text: "Nearly straight, with a fixed soft bend the whole rep." },
      { part: "Core", text: "Braced to keep the torso still." },
    ],
    cues: [
      "Hinge forward slightly, arms nearly straight with a fixed soft elbow bend.",
      "Sweep the bar down in a big arc to your thighs — the shoulder is the only joint that moves.",
      "Squeeze the lats hard at the bottom, then let the arms rise back overhead for a full stretch.",
      "Light weight. If you need to bend the elbows to move it, it's too heavy.",
    ],
    mistakes: [
      "Bending the elbows and turning it into a triceps pushdown.",
      "Standing bolt upright, which cuts the range in half.",
      "Rocking the torso to drive the bar down.",
    ],
  },

  {
    slug: "back-extension",
    name: "Back Extension",
    aka: "45° hyperextension — hold a plate to add load",
    gear: "Hyper bench",
    pattern: "Hip hinge",
    primary: ["hamstrings", "glutes", "lowerBack"],
    secondary: ["core"],
    tempo: 3.2,
    bodyPosition: [
      { part: "Head", text: "In line with your spine, eyes toward the floor." },
      { part: "Back", text: "One straight line from head to heels the whole rep." },
      { part: "Hips", text: "The joint that folds — the pad sits just below your hip bones." },
      { part: "Glutes", text: "Squeezed hard at the top." },
      { part: "Knees", text: "Soft, not locked." },
    ],
    cues: [
      "Set the pad just below the hip bones so you can hinge freely — too high and your lower back does all the work.",
      "The movement is a hip hinge: fold at the hips, keep the spine in one straight line from head to heels.",
      "Come up until your body is in line with your legs and stop. Don't arch up past straight.",
      "Squeeze the glutes at the top. Start bodyweight, then hug a plate to your chest as it gets easy.",
    ],
    mistakes: [
      "Cranking into hyperextension at the top, which is where people tweak their back.",
      "Rounding down through the spine instead of hinging at the hip.",
      "Jerking up with momentum, especially once you add a plate.",
    ],
  },

  {
    slug: "shrugs",
    name: "Shrugs",
    gear: "Barbell / Dumbbells",
    pattern: "Scapular elevation",
    primary: ["traps"],
    secondary: ["forearms"],
    tempo: 2.6,
    bodyPosition: [
      { part: "Head", text: "Neutral, not craning forward as you shrug." },
      { part: "Shoulders", text: "Rise straight up toward your ears, then drop all the way down between reps." },
      { part: "Arms", text: "Straight, just acting as hooks — no pulling with the biceps." },
      { part: "Torso", text: "Upright and still." },
    ],
    cues: [
      "Shrug straight up toward your ears — the traps elevate, they don't rotate.",
      "Pause for a second at the top; that squeeze is the whole exercise.",
      "Arms stay straight and act as hooks. No pulling with the biceps.",
      "Let the shoulders drop all the way down between reps for a full stretch.",
    ],
    mistakes: [
      "Rolling the shoulders backward — adds nothing and irritates the joint.",
      "Bouncing tiny reps with far too much weight.",
      "Craning the neck forward as you shrug.",
    ],
  },
];
