import type { Exercise } from "../types";

export const chest: Exercise[] = [
  {
    slug: "chest-press",
    name: "Chest Press",
    aka: "Machine chest press",
    gear: "Machine",
    pattern: "Horizontal press",
    primary: ["chest"],
    secondary: ["frontDelts", "triceps"],
    tempo: 3,
    bodyPosition: [
      { part: "Head", text: "Resting back against the pad, eyes forward." },
      { part: "Shoulders", text: "Pulled back and down, pinned into the pad — not rolled forward." },
      { part: "Chest", text: "Lifted up toward the handles." },
      { part: "Elbows", text: "Bent to about 90° at the start, not flared out to the sides." },
      { part: "Back", text: "Flat against the seat, no arching." },
      { part: "Feet", text: "Flat on the floor, about hip width." },
    ],
    cues: [
      "Set the seat so the handles are level with the middle of your chest, not your collarbones.",
      "Pull your shoulder blades back and down into the pad. Chest up, shoulders back.",
      "Press until your elbows are almost straight, then stop. Don't let your shoulders roll forward.",
      "Lower slowly until you feel a stretch across your chest.",
    ],
    mistakes: [
      "Seat too low, so you press upward and it turns into a shoulder exercise.",
      "Elbows flared to 90°, which grinds the front of the shoulder.",
      "Letting the weight stack slam down and bouncing out of the bottom.",
    ],
  },

  {
    slug: "barbell-bench-press",
    name: "Barbell Bench Press",
    gear: "Barbell",
    pattern: "Horizontal press",
    primary: ["chest"],
    secondary: ["frontDelts", "triceps"],
    tempo: 3.4,
    bodyPosition: [
      { part: "Head", text: "Flat on the bench, chin tucked slightly — not craning to watch the bar." },
      { part: "Shoulders", text: "Pulled back and pinned down into the bench, like you're tucking them into your back pockets." },
      { part: "Chest", text: "Lifted up and slightly arched, so the bar meets your lower chest." },
      { part: "Elbows", text: "About 45–60° out from your torso, tucked rather than flared to 90°." },
      { part: "Lower back", text: "A small natural arch, glutes still touching the bench." },
      { part: "Feet", text: "Flat on the floor, pushed down hard for a stable base." },
    ],
    cues: [
      "Pull your shoulder blades back and down before you unrack. This protects your shoulders and gives you a stable base.",
      "Lower the bar to your lower chest, not your throat.",
      "Keep your elbows tucked, at about 45–60° from your torso. Don't flare them straight out.",
      "Push your feet into the floor. Keep your glutes on the bench the whole set.",
    ],
    mistakes: [
      "Bouncing the bar off the ribcage instead of controlling the touch.",
      "Elbows flaring to 90°, which puts the shoulder joint in its weakest position.",
      "Hips lifting off the bench on the heavy reps — that's the set telling you it's too heavy.",
    ],
  },

  {
    slug: "incline-chest-press",
    name: "Incline Chest Press",
    aka: "Incline machine or incline dumbbell press",
    gear: "Machine / Dumbbells",
    pattern: "Incline press",
    primary: ["upperChest"],
    secondary: ["frontDelts", "triceps"],
    tempo: 3,
    bodyPosition: [
      { part: "Head", text: "Resting on the bench, eyes up." },
      { part: "Bench angle", text: "30–45°, not steeper." },
      { part: "Shoulders", text: "Pulled back into the pad, not shrugged toward your ears." },
      { part: "Chest", text: "Lifted, aimed up toward the weights." },
      { part: "Elbows", text: "Kept in, not flared wide at the bottom of the rep." },
      { part: "Feet", text: "Flat on the floor for a stable base." },
    ],
    cues: [
      "Set the bench to 30–45°. Any steeper and your front shoulder takes over from your chest.",
      "Press up and slightly back, so the weights finish over your collarbones, not your face.",
      "Keep your shoulder blades pulled back into the pad. Don't let them creep up toward your ears.",
      "Lower until your elbows are level with your torso, then press back up.",
    ],
    mistakes: [
      "Setting the bench near-vertical, which turns it into an overhead press.",
      "Flaring the elbows wide at the bottom.",
      "Clanging the dumbbells together at the top and losing tension on the chest.",
    ],
  },

  {
    slug: "pec-deck-fly",
    name: "Pec Deck / Machine Fly",
    gear: "Machine",
    pattern: "Chest isolation",
    primary: ["chest"],
    secondary: ["frontDelts"],
    tempo: 3,
    bodyPosition: [
      { part: "Head", text: "Resting back against the pad." },
      { part: "Shoulders", text: "Back and down, away from your ears." },
      { part: "Chest", text: "Lifted and open toward the handles." },
      { part: "Elbows", text: "Soft, fixed bend the whole set — they don't straighten or bend further." },
      { part: "Upper arms", text: "Roughly level with your torso, not pressed forward." },
      { part: "Feet", text: "Flat on the floor." },
    ],
    cues: [
      "Keep a soft, fixed bend in your elbows the whole way. Only your shoulder should move.",
      "Chest up, shoulders back and down.",
      "Squeeze for a beat when the handles meet, then let them travel back slowly.",
      "Go lighter than you think. This exercise is about the stretch and the squeeze, not the weight.",
    ],
    mistakes: [
      "Bending and straightening the elbows, which quietly turns the fly into a press.",
      "Going too deep behind the torso and putting the shoulder capsule on stretch under load.",
      "Shrugging the shoulders up toward the ears as the handles come together.",
    ],
  },

  {
    slug: "dips",
    name: "Dips",
    gear: "Bodyweight / Parallel bars",
    pattern: "Vertical press",
    primary: ["chest", "triceps"],
    secondary: ["frontDelts"],
    tempo: 3.2,
    bodyPosition: [
      { part: "Head", text: "Neutral, looking forward or slightly down." },
      { part: "Torso", text: "Leaned forward 15–20° to bias the chest, or upright to bias the triceps." },
      { part: "Shoulders", text: "Pulled down away from your ears the whole way, even at the bottom." },
      { part: "Elbows", text: "Travel back alongside your body, not out to the sides." },
      { part: "Hips/legs", text: "Still — no swinging your legs for momentum." },
    ],
    cues: [
      "Lean forward about 15–20° to work your chest more, or stay upright to work your triceps more.",
      "Lower until your upper arm is about parallel to the floor. That's deep enough.",
      "Keep your shoulders down, away from your ears, even at the bottom. If they shrug up, you've gone too deep.",
      "Your elbows should travel back alongside you, not out to the sides.",
    ],
    mistakes: [
      "Dropping below parallel and letting the shoulders roll forward under load.",
      "Bouncing out of the bottom instead of controlling the turnaround.",
      "Swinging the legs to generate momentum.",
    ],
  },
];
