import type { Exercise } from "../types";

export const shoulders: Exercise[] = [
  {
    slug: "barbell-overhead-press",
    name: "Barbell Overhead Press",
    aka: "Standing military press",
    gear: "Barbell",
    pattern: "Vertical press",
    primary: ["frontDelts"],
    secondary: ["sideDelts", "triceps", "core"],
    tempo: 3,
    bodyPosition: [
      { part: "Head", text: "Pulled back to start, then pushed 'through the window' as the bar passes your face." },
      { part: "Shoulders", text: "Bar rests on the front delts to start, elbows slightly in front." },
      { part: "Core", text: "Braced hard, glutes squeezed — this is what holds you upright." },
      { part: "Arms", text: "Finish locked out overhead, biceps by your ears." },
      { part: "Lower back", text: "No leaning back — stay tall." },
      { part: "Feet", text: "Planted under the bar, roughly hip width." },
    ],
    cues: [
      "Start with the bar on your front shoulders, elbows slightly in front, forearms vertical.",
      "Squeeze your glutes and brace your abs. This stops you from leaning back as you press.",
      "Pull your head back to start. Press up, then move your head forward as the bar clears it.",
      "Finish with the bar over the middle of your foot, arms locked out by your ears.",
    ],
    mistakes: [
      "Leaning back through the lower back instead of bracing.",
      "Pressing the bar around your face in a big arc rather than moving your head.",
      "Stopping short overhead, with the bar still in front of the body.",
    ],
  },

  {
    slug: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    aka: "Alternate grip",
    gear: "Machine",
    pattern: "Vertical press",
    primary: ["frontDelts"],
    secondary: ["sideDelts", "triceps"],
    tempo: 3,
    bodyPosition: [
      { part: "Head", text: "Neutral, eyes forward." },
      { part: "Shoulders", text: "Handles start at about shoulder height, not above your ears." },
      { part: "Back", text: "Flat against the pad, ribs down — no arching to move the weight." },
      { part: "Grip", text: "Neutral or angled if the machine offers it — easier on the shoulder joint." },
      { part: "Feet", text: "Flat on the floor." },
    ],
    cues: [
      "Set the seat so the handles start at about shoulder height, not above your ears.",
      "Keep your back flat against the pad. Don't arch to get the weight moving.",
      "Use the angled handles if the machine has them. They're easier on your shoulders than a straight grip.",
      "Press until your arms are almost straight, then lower under control back to shoulder height.",
    ],
    mistakes: [
      "Starting far too low, which dumps you into the weakest part of the shoulder's range.",
      "Arching the lower back off the pad on the last few reps.",
      "Shrugging at the top instead of finishing with the shoulders down.",
    ],
  },

  {
    slug: "db-lateral-raise",
    name: "DB Lateral Raise",
    gear: "Dumbbells",
    pattern: "Shoulder abduction",
    primary: ["sideDelts"],
    secondary: ["traps"],
    tempo: 2.8,
    bodyPosition: [
      { part: "Head", text: "Neutral, eyes forward." },
      { part: "Torso", text: "Small forward tilt, no swinging." },
      { part: "Shoulders", text: "Stay down — don't let them creep up toward your ears." },
      { part: "Elbows", text: "Lead the movement, a touch higher than your wrists at the top." },
      { part: "Arms", text: "Raise out and slightly forward, to shoulder height, no higher." },
    ],
    cues: [
      "Raise to shoulder height and no higher. Going higher hands the work to your traps.",
      "Lead with your elbows, not your hands. Your elbow should sit a touch higher than your wrist at the top.",
      "Raise the weights slightly in front of your body, not straight out to the side.",
      "Tilt your torso forward a little and don't swing. Use a lighter weight than you want to.",
    ],
    mistakes: [
      "Swinging the weights up with a hip bounce.",
      "Going above shoulder height and turning it into a shrug.",
      "Leading with the hands, wrists higher than elbows, which shifts it to the front delt.",
    ],
  },

  {
    slug: "rear-delt-fly",
    name: "Rear Delt Fly",
    aka: "Reverse pec deck, or crossed cables",
    gear: "Machine / Cable",
    pattern: "Horizontal abduction",
    primary: ["rearDelts"],
    secondary: ["upperBack"],
    tempo: 3,
    bodyPosition: [
      { part: "Head", text: "Neutral, resting forward against the pad if there is one." },
      { part: "Chest", text: "Against the pad, torso still." },
      { part: "Shoulders", text: "The back of the shoulder leads — not a shoulder-blade squeeze." },
      { part: "Elbows", text: "Small, constant bend the whole rep." },
      { part: "Arms", text: "Sweep out and back at roughly shoulder height, thumbs pointing slightly down." },
    ],
    cues: [
      "Chest against the pad. Keep a small, constant bend in your elbows the whole set.",
      "Sweep your arms out and back at roughly shoulder height, thumbs pointing slightly down.",
      "Focus on pulling with the back of your shoulder, not squeezing your shoulder blades together.",
      "Use a very light weight. This exercise is about control, not load.",
    ],
    mistakes: [
      "Bending the elbows through the rep so it becomes a wide row.",
      "Letting the arms drop low so the lats take over.",
      "Jerking the torso off the pad to move heavier weight.",
    ],
  },

  {
    slug: "cable-face-pull",
    name: "Cable Face Pull",
    gear: "Cable",
    pattern: "Horizontal pull, high",
    primary: ["rearDelts"],
    secondary: ["upperBack", "traps"],
    tempo: 3,
    bodyPosition: [
      { part: "Head", text: "The rope finishes pointing at your forehead." },
      { part: "Elbows", text: "Stay at shoulder height — this is a high pull, not a row to the chest." },
      { part: "Hands", text: "Split apart as they arrive beside your ears, knuckles finishing up and back." },
      { part: "Torso", text: "Upright, no leaning back to use bodyweight." },
      { part: "Feet", text: "Staggered or hip width, stepped back so there's tension at the start." },
    ],
    cues: [
      "Set the pulley at roughly face height. Step back so there's tension before you start pulling.",
      "Pull the rope toward your forehead. Split your hands apart as they reach your ears.",
      "Keep your elbows at shoulder height. This is a high pull, not a row to your chest.",
      "Rotate your hands at the end so your knuckles point up and back. Hold for a beat.",
    ],
    mistakes: [
      "Letting the elbows drop, which turns it into an upper-back row and skips the rear delts.",
      "Leaning back and using bodyweight as a counterweight.",
      "Too much load, so the reps become a series of jerks.",
    ],
  },
];
